[env:es3c28p]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
 
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
monitor_speed = 115200
upload_speed = 921600
 
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE
    -DCORE_DEBUG_LEVEL=1
    -I include
 
lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    lvgl/lvgl@^8.3.11
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.0

extra_scripts = pre:scripts/patch_libs.py
 